version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    restart: always
    env_file: .env
    ports:
      - "${CHROMA_PORT}:8000"
      - "${GRPC_PORT}:8001"
    volumes:
      - ./chroma_data:/chroma

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    volumes:
      - .:/workspace
    depends_on:
      - postgres
      - chroma
    command: ["sleep", "infinity"] # keeps container running for dev/debug

volumes:
  postgres_data:
  pgadmin_data:
